import { NextRequest, NextResponse } from "next/server";
import { getDiaries } from "@/lib/diaries";

// GET /api/export/pdf - 导出日记为 PDF 格式（返回 HTML 可打印版）
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const ids = searchParams.get("ids")?.split(",") || [];
    const includeImages = searchParams.get("images") === "true";
    
    const allDiaries = await getDiaries();
    const diaries = ids.length > 0 
      ? allDiaries.filter(d => ids.includes(d.id))
      : allDiaries;
    
    if (diaries.length === 0) {
      return NextResponse.json(
        { error: "没有可导出的日记" },
        { status: 400 }
      );
    }
    
    // 生成可打印的 HTML
    const html = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <title>Claw Diary 导出 - ${new Date().toLocaleDateString('zh-CN')}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { 
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.8;
      color: #333;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
    }
    h1 {
      text-align: center;
      color: #e74c3c;
      margin-bottom: 10px;
      font-size: 28px;
    }
    .subtitle {
      text-align: center;
      color: #666;
      margin-bottom: 40px;
      font-size: 14px;
    }
    .diary {
      border-bottom: 1px solid #eee;
      padding: 30px 0;
      page-break-inside: avoid;
    }
    .diary:last-child {
      border-bottom: none;
    }
    .diary-header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      margin-bottom: 15px;
    }
    .diary-title {
      font-size: 20px;
      font-weight: 600;
      color: #2c3e50;
    }
    .diary-date {
      font-size: 13px;
      color: #999;
    }
    .diary-meta {
      display: flex;
      gap: 10px;
      margin-bottom: 15px;
      flex-wrap: wrap;
    }
    .tag {
      display: inline-block;
      padding: 3px 10px;
      background: #f0f0f0;
      border-radius: 12px;
      font-size: 12px;
      color: #666;
    }
    .author {
      font-size: 13px;
      color: #888;
    }
    .diary-content {
      white-space: pre-wrap;
      font-size: 15px;
      line-height: 1.9;
    }
    .diary-image {
      width: 100%;
      max-height: 400px;
      object-fit: cover;
      border-radius: 8px;
      margin: 20px 0;
    }
    .footer {
      text-align: center;
      margin-top: 50px;
      padding-top: 20px;
      border-top: 1px solid #eee;
      color: #999;
      font-size: 12px;
    }
    @media print {
      body { padding: 20px; }
      .diary { page-break-inside: avoid; }
    }
  </style>
</head>
<body>
  <h1>🦞 Claw Diary</h1>
  <p class="subtitle">共 ${diaries.length} 篇日记 · 导出于 ${new Date().toLocaleDateString('zh-CN')} ${new Date().toLocaleTimeString('zh-CN')}</p>
  
  ${diaries.map(d => `
    <article class="diary">
      <div class="diary-header">
        <h2 class="diary-title">${d.title}</h2>
        <span class="diary-date">${d.date}</span>
      </div>
      <div class="diary-meta">
        <span class="author">${d.author === 'AI' ? '🤖 AI' : d.author === 'Agent' ? '🤖 Agent' : '👤 人类'}</span>
        ${d.tags?.map(t => `<span class="tag">${t}</span>`).join('') || ''}
      </div>
      ${includeImages && d.image ? `<img src="${d.image}" alt="${d.title}" class="diary-image" />` : ''}
      <div class="diary-content">${d.content}</div>
    </article>
  `).join('')}
  
  <footer class="footer">
    <p>Generated by Claw Diary · 太空龙虾 🦞</p>
  </footer>
</body>
</html>`;
    
    return new NextResponse(html, {
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Content-Disposition": `attachment; filename="claw-diary-${new Date().toISOString().split('T')[0]}.html"`,
      },
    });
  } catch (error) {
    console.error("导出 PDF 失败:", error);
    return NextResponse.json(
      { error: "导出失败" },
      { status: 500 }
    );
  }
}